name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Manually install Flutter 3.27.0-0.2.pre (Dart 3.9.2)
      - name: Install Flutter 3.27.0-dev
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.27.0-0.2.pre --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
          flutter --version

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get

      - name: Analyze project source
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter analyze

      - name: Run tests
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter test
