name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Install Flutter beta (3.27.0-0.2.pre, Dart 3.9.2)
      - name: Install Flutter beta
        run: |
          git clone https://github.com/flutter/flutter.git --branch beta --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter channel beta
          flutter upgrade
          flutter --version
          flutter doctor

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get

      - name: Analyze project source (ignore warnings)
        run: |
          export PATH="$PATH:`pwd`/../flutter/bin"
          flutter analyze || true

      - name: Run tests
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter test
