name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Manually install Flutter 3.27.0-dev.1.0 (includes Dart 3.9.2)
      - name: Install Flutter 3.27.0-dev.1.0
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.27.0-0.2.pre --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
