name: Performance Regression Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  perf-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyzer + unit tests
        run: flutter analyze ; flutter test --coverage

      - name: Performance tests
        run: flutter test test/performance/perf_harness_test.dart
